### ISSUE TITLE
Return Iterator

### ISSUE THREAD

**Issue by mikail-khan** [melrief/PureCSV#16]
Hi,

Is it possible to return an iterator using readCSVFromFile? If I am correct, it returns a List() with all contents of the file loaded into memory. Ideally I would like to get something like getLines from io.Source which returns an iterator.

**Comment by melrief** [comment]
Yes, the `readCSVFromFile` should be rewritten in

```scala
    def readCSVFromFile(f: File,
                        delimiter:Char = RecordSplitter.defaultFieldSeparator,
                        skipHeader: Boolean = false): List[Try[A]] = {
      val r = new BufferedReader(new FileReader(f))
      val rs = readCSVFromReader(r, delimiter, skipHeader)
      r.close()
      rs
}
```

The core function is `readCSVFromReader` with correctly works on `Iterator`.
