### ISSUE TITLE
Should this fail?

### ISSUE THREAD

**Issue by mikail-khan** [melrief/PureCSV#17]
Given the following data structure:

case class Foo(a : Int, b : String)

This fails on pure parsing:

"A", 1

but this passes

"A",1

Notice the space after the comma in the first example.

Is the library behaving as expected here?

**Comment by melrief** [comment]
No, it isn't behaving as aspected. Not sure why this happens considering that I'm using OpenCSV exactly to delegate to it the parsing of the fields.
