### ISSUE TITLE
This is not Working On Option Field

### ISSUE THREAD

**Issue by Uditmittal** [melrief/PureCSV#2]
case class t(id:Option[Int],name:String)
val T=t(Some(1),"err")
     Ok(T.toCSV()) 

[error] /home/udit/git/scaler/scaler/backend/app/testcontroller/TestController.scala:114: value toCSV is not a member of testcontroller.TestController.t
[error]      Ok(T.toCSV())  
[error]           ^
[error] one error found
[error](compile:compile) Compilation failed

**Comment by melrief** [comment]
I'm going to work on this tonight

**Comment by melrief** [comment]
Implemented in 5f98d46
