### ISSUE TITLE
Failed with datatypes of java.util.UUID, and java.sql.Timestamp.

### ISSUE THREAD

**Issue by kirankumar-dasari** [melrief/PureCSV#23]
Sample code snippet for reference:

    import purecsv.safe._

    case class Sample(/*id: UUID, */ string: Option[String] = None,
                      number: Double,
                      integer: Int,
                      boolean: Option[Boolean] = Some(false) /*,
                      timestamp: Option[Timestamp] = None*/
                     )

    var csvLines = Seq(
      Sample(/*UUID.randomUUID(), */ Some("String"), 10.0, 10),
      Sample(/*UUID.randomUUID(), */ Some("String"), 10.0, 10, Some(true))
    ).toCSVLines()

    for (csvLine <- csvLines)
      println(csvLine)

**Comment by melrief** [comment]
There is no support for the datatypes yet. The supported types are [here](https://github.com/melrief/PureCSV/blob/master/shared/src/main/scala/purecsv/safe/converter/defaults/string/package.scala#L20). You can however add your own implicit converter and the library will pick it automatically.
