### ISSUE TITLE
toCSV() is not a member of 

### ISSUE THREAD

**Issue by psyanite** [melrief/PureCSV#24]
Hi I came across your library and thought it's clean and great!

How come I get this error?

![image](https://cloud.githubusercontent.com/assets/24215698/25560652/ab5f5316-2d9d-11e7-9111-9c7478ab5690.png)

I've added the import statement.
import purecsv.safe._

**Comment by melrief** [comment]
There is no `Converter` for `Try`, consequently there is no `.toCSV()` that can be added to your `records`. If you want to support it then you have to add an implicit converter, something like [this](https://github.com/melrief/PureCSV/blob/master/shared/src/main/scala/purecsv/safe/converter/defaults/string/package.scala#L25). A blueprint:

```scala
 implicit def trySC[A](implicit val sc: StringConverter[A]): StringConverter[Try[A]] = /* your code here... */
```

**Comment by psyanite** [comment]
Hi melrief, thank you for your response and the code snippet provided!
