### ISSUE TITLE
Publish 0.0.2

### ISSUE THREAD

**Issue by mfirry** [melrief/PureCSV#3]
I can't find 0.0.2 on Sonatype nexus.
Thank you!

**Comment by melrief** [comment]
I'm traveling, I'll publish the artifact tonight late or tomorrow

**Comment by mfirry** [comment]
No rush. Take your time. Thanks!

**Comment by pfriesch** [comment]
For everyone who can't wait, you can add sbt repositories directly in your `build.sbt`:

``` scala
lazy val root = (project in file(".")).dependsOn(pureCSV)
lazy val pureCSV = RootProject(uri("https://github.com/melrief/PureCSV.git"))
```

**Comment by melrief** [comment]
0.0.2 released on sonatype, sorry for the delay
