### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by h0ffmann** [melrief/PureCSV#36]
I would like to give 2 suggestions:

1 - Give the option of using the case classes fields as header of the CSV file using reflection

2 - Option to persist string fields with/without delimiters such as "" that sometimes could be unnecessary

Can I do this and submit the PR?

**Comment by pjfanning** [comment]
We've implemented versions of these features in https://github.com/kontainers/PureCSV/releases/tag/v0.3.1 (a forked version of PureCSV)
