### ISSUE TITLE
scalajs support

### ISSUE THREAD

**Issue by antonkulaga** [melrief/PureCSV#6]
scalajs support would be very useful

**Comment by melrief** [comment]
I have to explore the support for shapeless from scalajs but if it works I could make pure-csv work with that too. I'm not sure when I'll be able to work on it

**Comment by antonkulaga** [comment]
@melrief please look at my [scalajs branch](https://github.com/antonkulaga/PureCSV/tree/scalajs) The only problem there is that opencvs does not work for scalajs (as it is unported java library). Could you consider providing its scala alternative? Actually another CVS lib already did that ( see https://github.com/marklister/product-collections/blob/master/shared/src/main/scala/collections/io/CSVReader.scala ). Maybe you can even join forces with them? I like product collections for their...ehm...tuple collections and scalajs support. But your library has case-classes macroses that are better for some usecases

**Comment by antonkulaga** [comment]
any progress in ScalaJS direction?

**Comment by melrief** [comment]
Not yet, but I should work on this next. The idea is to have a quick look at your branch and merge it if all tests pass.

**Comment by melrief** [comment]
PR #10 is working, I will merge it if Travis says that everything is ok. About merging my work in product-collections, I first of all have to talk with them. In the meanwhile, @antonkulaga thanks for your contribution! Can I add you to the contributors file?

**Comment by melrief** [comment]
Released 0.0.5 with support for scalajs
