### ISSUE TITLE
update to last shapeless version

### ISSUE THREAD

**Issue by sergius** [melrief/PureCSV#7]
Hi Mario,

I find this a great library but currently I have to override its `shapeless` dependency (to v. 2.1.0) because we use the latest version (2.2.4) across the project, the compiler finds them incompatible and evicts the library. Could you update it, please.
I made a quick test changing the dependency locally to 2.2.4 (which also forced the update of `scala` to 2.11.7) and it compiles and runs the tests without issues, but perhaps there are more details to be considered that I don't know.

Thanks!

**Comment by melrief** [comment]
Sure, I'll do it right now.

**Comment by sergius** [comment]
Great! Thanks again.

**Comment by melrief** [comment]
Done and published version 0.0.3. Let me know if it works! In the meanwhile, I'm closing this.

**Comment by sergius** [comment]
Works like a charm :+1:
